name: GitHub Pages

on:
  push:
    branches:
      - source-code
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter --version

      # - name: Setup Flutter
      #   run: |
      #     git clone https://github.com/flutter/flutter.git --depth 1 -b beta _flutter
      #     echo "${GITHUB_WORKSPACE}/_flutter/bin" >> ${GITHUB_PATH}

      - name: Install
        run: |
          flutter config --enable-web
          flutter pub get
          flutter doctor -v

      - name: Build
        run: flutter build web --pwa-strategy offline-first --dart-define=FLUTTER_WEB_USE_SKIA=true --web-renderer auto --profile

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/source-code' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
